name: build

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 'Build blog and deploy to gihtub pages'
      uses: reuixiy/hugo-deploy@v1
      env:
        DEPLOY_REPO: heisantosh/heisantosh.github.io
        DEPLOY_BRANCH: build
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        TZ: Asia/Kolkata